config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :ski_places, only: [:show, :new, :create]

  get '/resources' => 'static_pages#resources'
  get '/safety' => 'static_pages#safety'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  namespace :api do
    namespace :v1 do
      resources :avalanche_forecast_zones, only: [:index, :show]
      resources :snotel_stations, only: [:index, :show]
      resources :ski_places, only: [:index, :show]
    end
  end

end

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="/" class="logo">
      <img src="https://s3-us-west-1.amazonaws.com/cobackcountry/cobackcountry_logo_no_word_CO.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><%= link_to "About Us", about_path %></li>
        <li class="nav-link"><%= link_to "Contact", contact_path %></li>
        <li class="nav-link"><%= link_to "New Route", new_ski_place_path %></li>

      </ul>
    </div>
  </div>
</header>

<script>
  $(function() {
    var menu = $('#navigation-menu');
    var menuToggle = $('#js-mobile-menu');
    var signUp = $('.sign-up');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });

    // underline under the active nav item
    $(".nav .nav-link").click(function() {
      $(".nav .nav-link").each(function() {
        $(this).removeClass("active-nav-item");
      });
      $(this).addClass("active-nav-item");
      $(".nav .more").removeClass("active-nav-item");
    });
  });
</script>

app/views/refills/_type-system-serif.html.erb
<head>
  <link href='http://fonts.googleapis.com/css?family=Lusitana:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather+Sans:400,300,300italic,400italic,700italic,700,800,800italic' rel='stylesheet' type='text/css'>
</head>

<article class="type-system-serif">
  <%= partial "type-system-content" %>
</article>